CREATE TABLE enderecos (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  cep varchar(8),
  uf varchar(2),
  cidade text,
  bairro text,
  logradouro text,
  numero text
);

CREATE TABLE estabelecimentos (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  endereco_id integer REFERENCES enderecos(id)
);

CREATE TABLE categorias (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  nome text NOT NULL,
  descricao text NOT NULL
);

CREATE TABLE tipos_pagamento (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  tipo text NOT NULL UNIQUE
);

CREATE TABLE despesas (
  id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  valor numeric(12,2) NOT NULL,
  data_compra date NOT NULL,
  descricao text NOT NULL,
  tipo_pagamento_id integer NOT NULL REFERENCES tipos_pagamento(id),
  categoria_id integer NOT NULL REFERENCES categorias(id),
  estabelecimento_id integer REFERENCES estabelecimentos(id)
);
