import 'dotenv/config';
import { Pool } from 'pg';
import { env } from '../src/config/env';

const pool = new Pool({
  host: env.DB_HOST,
  port: env.DB_PORT,
  database: env.DB_NAME,
  user: env.DB_USER,
  password: env.DB_PASSWORD,
});

async function setup() {
  const client = await pool.connect();

  try {
    console.log('Creating schema...');
    await client.query(`
      CREATE TABLE IF NOT EXISTS enderecos (
        id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        cep varchar(8),
        uf varchar(2),
        cidade text,
        bairro text,
        logradouro text,
        numero text
      );

      CREATE TABLE IF NOT EXISTS estabelecimentos (
        id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        endereco_id integer REFERENCES enderecos(id)
      );

      CREATE TABLE IF NOT EXISTS categorias (
        id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        nome text NOT NULL,
        descricao text NOT NULL
      );

      CREATE TABLE IF NOT EXISTS tipos_pagamento (
        id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        tipo text NOT NULL UNIQUE
      );

      CREATE TABLE IF NOT EXISTS despesas (
        id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        valor numeric(12,2) NOT NULL,
        data_compra date NOT NULL,
        descricao text NOT NULL,
        tipo_pagamento_id integer NOT NULL REFERENCES tipos_pagamento(id),
        categoria_id integer NOT NULL REFERENCES categorias(id),
        estabelecimento_id integer REFERENCES estabelecimentos(id)
      );
    `);

    console.log('Seeding data...');
    await client.query(`
      INSERT INTO tipos_pagamento (tipo) VALUES
        ('Dinheiro'),
        ('Débito'),
        ('Crédito'),
        ('Pix')
      ON CONFLICT (tipo) DO NOTHING;
    `);

    console.log('Database setup complete.');
  } finally {
    client.release();
    await pool.end();
  }
}

setup().catch((err) => {
  console.error('Database setup failed:', err);
  process.exit(1);
});
